<?php
	$id=$this->getId();
	$sgc = Mage::getSingleton('customer/session')->getCustomer();
	$email= $sgc->getEmail();
	$name = $sgc -> getName();
	$startdate= time();
	$enddate = time ( ) + (30 * 24 *60*60);
//mysql login
	$db_hostname = 'hostname';
	$db_database = 'databasename';	
	$db_username = 'username';
	$db_password = 'password';
// connect to testsitedaily db
    $db_server = mysql_connect($db_hostname, $db_username, $db_password);
    if (!$db_server) die("Unable to connect to MySQL: " . mysql_error());
    mysql_select_db($db_database)
    or die("Unable to select database: " . mysql_error());
	$email = mysql_real_escape_string($email);
	
			// query for super account script ids
		if($id==2)
		{
		   $query = "select script_id from selenium_scripts";
	       $result = mysql_query($query);
     	   if (!$result) die ("Database access failed: " . mysql_error());
		}
		else
		{
		
// query for script ids
	        $query = "select script_id from selenium_scripts where customer_id=".$id;
	        $result = mysql_query($query);
	        if (!$result) die ("Database access failed: " . mysql_error());
		}
			// number of rows returned
        $rows = mysql_num_rows($result);
		//echo $rows;
		if($rows==0)
		{
			echo " </br>Welcome to the family! We are processing your request and your script will be ready shortly.</br></br>";
		}
		 	$row = mysql_fetch_row($result);
			//var_dump($row);
			
		for ($j = 0 ; $j < $rows ; ++$j)
		{
			$queryforgraph = mysql_query("SELECT SUBSTRING(lastsampleat,1,CHAR_LENGTH(lastsampleat)-8) AS lastsampleat,avguptimeweek FROM selenium_script_data where selenium_id='".$row[0]."' order by lastsampleat ASC");
    		$resultforgraph = mysql_fetch_row($queryforgraph);
			$queryfordata = "select lastsampleat,generalstatus,lasterrorat,avguptimeweek,avgLoadtimeday from selenium_script_data where selenium_id='".$row[0]."' order by sno DESC";
			$resultqfd = mysql_query($queryfordata);
			$rowsgraph = array();
			//flag is not needed
			$flaggraph = true;
			$tablegraph = array();
			$tablegraph['cols'] = array(
		    // Labels for your chart, these represent the column titles
		    // Note that one column is in "string" format and another one is in "number" format as pie chart only required "numbers" for calculating percentage and string will be used for column title
    		array('label' => 'Date', 'type' => 'string'),
		    array('label' => 'Percentage', 'type' => 'number')
			);	
			$rowsgraph = array();
			while($r = mysql_fetch_assoc($queryforgraph)) 
			{
		    	$tempgraph = array();
			    // the following line will be used to slice the Pie chart
			    $tempgraph[] = array('v' => (string) $r['lastsampleat']); 
			    // Values of each slice
			    $tempgraph[] = array('v' => (int) $r['avguptimeweek']); 
			    $rowsgraph[] = array('c' => $tempgraph);
			}
			$tablegraph['rows'] = $rowsgraph;
			$jsonTable = json_encode($tablegraph);
			//echo $jsonTable;
echo <<<_END
    <script type="text/javascript">
    // Load the Visualization API and the piechart package.
    google.load('visualization', '1', {'packages':['corechart']});
    // Set a callback to run when the Google Visualization API is loaded.
    google.setOnLoadCallback(drawChart);
    function drawChart() {
      // Create our data table out of JSON data loaded from server.
      var data = new google.visualization.DataTable($jsonTable);
      var options = {
           title: 'Date vs Percentage',
           is3D: 'true',
           width: 800,
           height: 400,
		   animation:{  duration: 1000, easing: 'out'}
           };
      // Instantiate and draw our chart, passing in some options.
      // Do not forget to check your div ID
      var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
      chart.draw(data, options);
	 //setInterval(drawChart, 500 );
    }
    </script>
<div class="dashcontainer">
<h3 class="monitorsummary">Monitor Summary</h3>
<table   style="width:54%;margin:40px 0px 0px 50px;height:135px;padding:10px;line-height:50px;text-align:right;font-size:12px;font-family:Arial;border-collapse:collapse;border-bottom:1px solid #d9d5be" id="my-orders-table">
 
<thead style="font-size:12px;color:#444444;vertical-align:middle;border-bottom:2px solid #444444">
            <tr>
                <th>Sno.</th>
                <th>Date</th>
                <th>Status</th>
		  <th>Last Error At</th>
		  <th>Avg Up Time Week(%)</th>
		  <th>Avg Load Time Day (ms)</th>
             <!--   <th>Sample time</span></th>
                <th>Status</th>
                <th>&nbsp;</th>-->
            </tr>
        </thead>
        <tbody>
_END;
	for($i=0;$i<3;$i++)
	{	
		$rowqfd=mysql_fetch_row($resultqfd);
		echo <<<_END
                           <tr style="border-bottom:1px solid #d9d5be">
                    <td>
_END;
echo $i+1;
echo <<<_END
</td>
                    <td>
_END;
$date = substr($rowqfd[0],0,10);
echo $date;
//echo $rowqfd[0];
echo <<<_END
</td>
                  <td>
_END;
if($rowqfd[1]=="SUCCESS")
{
echo <<<_END
<div class="data-status active"></div>
_END;
}
elseif($rowqfd[1]=="ERROR")
{
echo <<<_END
<div class="data-status alerting"></div>
_END;
}
else
{
echo <<<_END
<div class="data-status off"></div>
_END;
}
echo <<<_END
                 </td>
                  <td>
_END;
$date = substr($rowqfd[2],0,10);
echo $date;
//echo $rowqfd[2];
echo <<<_END
                 </td>
                  <td>
_END;
echo $rowqfd[3];
echo <<<_END
                 </td>
                  <td>
_END;
echo $rowqfd[4];
echo <<<_END
                 </td>
                  <td>

                 </td>
</tr>
_END;
}
echo <<<_END
</tbody>
</table>

_END;
 
};
?></strong></p>

</div>

    <div id="chart_div"></div>

</div>
